name = "cdn3-dev"
main = "src/index.ts"
compatibility_date = "2023-05-10"
compatibility_flags = ["nodejs_compat"]
logpush = true

# Specifies the r2 buckets. r2 bucket names are scoped to your account (not global). The buckets should be publicly inaccessible.
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "media-staging", preview_bucket_name = "media-staging" },
    { binding = "BACKUP_BUCKET", bucket_name = "backups-staging", preview_bucket_name = "backups-staging" }
]

durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]

[[migrations]]
tag = "v1"
new_classes = ["UploadHandler"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "UploadHandler", to = "AttachmentUploadHandler" }]
new_classes = ["BackupUploadHandler"]

[env.production]
name = "cdn3"
durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "media", preview_bucket_name = "media" },
    { binding = "BACKUP_BUCKET", bucket_name = "backups", preview_bucket_name = "backups" }
]

[env.staging]
name = "cdn3-staging"
durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "media-staging", preview_bucket_name = "media-staging" },
    { binding = "BACKUP_BUCKET", bucket_name = "backups-staging", preview_bucket_name = "backups-staging" }
]

# To set an auth secret,
# wrangler secrets put SHARED_AUTH_SECRET 
